local cards = {
    poison_arrow = {
        cost          = 3,
        type          = 'range',
        drop_to       = 'grave',
        use_condition = 'select 1 enemy',
        data          = { atk = 1 },
        effect        = {'atk(card.data.atk) to target' ,'add_buff (poison(round:2)) to target'},
    },
    throw_axe =   {
        cost          = 4,
        type          = 'melee',
        drop_to       = 'grave',
        use_condition = { 'select 1 enemy ', 'input 2 hand_card' },
        data          = { atk = 'holder.data.atk * 1.5 ' },
        effect        = { 'atk(card.data.atk) to target' },
    },
    defense =   {
        cost          =  2,
        type          =  'melee',
        drop_to       =  'grave',
        use_condition =  {'select 1 hero'},
        data          =  {def = 3},
        effect        =  {'def(card.data.def) to target'},
    },
    attack =   {
        cost          =  1,
        type          =  'melee',
        drop_to       =  'grave',
        use_condition =  {'select 1 enemy'},
        data          =  {atk = 3},
        effect        =  {'atk(card.data.atk) to target'},
    },
    ignore_shield_attack =   {
        cost          =  1,
        type          =  'melee',
        drop_to       =  'grave',
        use_condition =  {'select 1 enemy'},
        data          =  {atk = 1},
        effect        =  {'ignore_shield_attack(card.data.atk) to target'},
    },
    weakness_attack   =   {
        cost          =  1,
        type          =  'melee',
        drop_to       =  'grave',
        use_condition =  {'select 1 enemy'},
        data          =  {atk = 2},
        condition 	  =  'target.data.shield <= 0',
        effect        =  {'condition (true:atk(card.data.atk * 2) to target ,false:atk(card.data.atk ) to target)'}
    },
    rapid_fire        =   {
        cost          =  1,
        type          =  'melee',
        drop_to       =  'grave',
        use_condition =  {'select 1 enemy'},
        data          =  {atk = 2},
        effect        =  {'jump(2) atk(card.data.atk) to target'},
    },
    random_atk        =   {
        cost          =  1,
        type          =  'melee',
        drop_to       =  'grave',
        use_condition =  {'select 1 enemy'},
        data          =  {atk = 2},
        effect        =  {'atk(random(1~3)) to target'},
    },
    solid        =   {
        cost          =  1,
        type          =  'melee',
        drop_to       =  'grave',
        use_condition =  {'select 1 hero'},
        data          =  {atk = 2},
        effect        =  {'add_buff (solid(round:2)) to target'},
    },
}
return cards
